const users = [
    {
        "id": 1,
        "first_name": "Garrik",
        "last_name": "Skippon",
        "email": "gskippon0@blogger.com",
        "gender": "Male",
        "ip_address": "34.213.252.141"
    }, {
        "id": 2,
        "first_name": "Maje",
        "last_name": "Blyden",
        "email": "mblyden1@dyndns.org",
        "gender": "Male",
        "ip_address": "229.35.26.150"
    }, {
        "id": 3,
        "first_name": "Leslie",
        "last_name": "Millmoe",
        "email": "lmillmoe2@example.com",
        "gender": "Male",
        "ip_address": "243.73.33.209"
    }, {
        "id": 4,
        "first_name": "Ikey",
        "last_name": "Martyn",
        "email": "imartyn3@twitpic.com",
        "gender": "Male",
        "ip_address": "121.226.0.239"
    }, {
        "id": 5,
        "first_name": "Ingaborg",
        "last_name": "Marflitt",
        "email": "imarflitt4@furl.net",
        "gender": "Female",
        "ip_address": "112.72.44.104"
    }, {
        "id": 6,
        "first_name": "Mauricio",
        "last_name": "Flaverty",
        "email": "mflaverty5@smugmug.com",
        "gender": "Male",
        "ip_address": "140.8.206.113"
    }, {
        "id": 7,
        "first_name": "Florenza",
        "last_name": "Rosbottom",
        "email": "frosbottom6@simplemachines.org",
        "gender": "Female",
        "ip_address": "12.102.151.5"
    }, {
        "id": 8,
        "first_name": "Eduardo",
        "last_name": "Ilyin",
        "email": "eilyin7@fotki.com",
        "gender": "Male",
        "ip_address": "156.161.213.212"
    }, {
        "id": 9,
        "first_name": "Kasey",
        "last_name": "McIlreavy",
        "email": "kmcilreavy8@freewebs.com",
        "gender": "Female",
        "ip_address": "167.216.85.158"
    }, {
        "id": 10,
        "first_name": "Huntley",
        "last_name": "Poley",
        "email": "hpoley9@nationalgeographic.com",
        "gender": "Male",
        "ip_address": "167.157.95.33"
    }, {
        "id": 11,
        "first_name": "Tobye",
        "last_name": "Prest",
        "email": "tpresta@adobe.com",
        "gender": "Female",
        "ip_address": "198.111.251.189"
    }, {
        "id": 12,
        "first_name": "Chev",
        "last_name": "Coatman",
        "email": "ccoatmanb@cisco.com",
        "gender": "Male",
        "ip_address": "59.181.236.23"
    }, {
        "id": 13,
        "first_name": "Horacio",
        "last_name": "Ludvigsen",
        "email": "hludvigsenc@geocities.com",
        "gender": "Male",
        "ip_address": "84.77.244.85"
    }, {
        "id": 14,
        "first_name": "Krystal",
        "last_name": "Bengough",
        "email": "kbengoughd@cdc.gov",
        "gender": "Genderqueer",
        "ip_address": "240.254.94.63"
    }, {
        "id": 15,
        "first_name": "Colver",
        "last_name": "Brach",
        "email": "cbrache@nifty.com",
        "gender": "Male",
        "ip_address": "192.88.1.3"
    }, {
        "id": 16,
        "first_name": "Katine",
        "last_name": "Mellon",
        "email": "kmellonf@ning.com",
        "gender": "Female",
        "ip_address": "165.31.176.129"
    }, {
        "id": 17,
        "first_name": "Marley",
        "last_name": "Ephson",
        "email": "mephsong@cnet.com",
        "gender": "Female",
        "ip_address": "44.224.73.3"
    }, {
        "id": 18,
        "first_name": "Emmett",
        "last_name": "Baston",
        "email": "ebastonh@wp.com",
        "gender": "Male",
        "ip_address": "46.63.255.80"
    }, {
        "id": 19,
        "first_name": "Flinn",
        "last_name": "Williscroft",
        "email": "fwilliscrofti@1688.com",
        "gender": "Male",
        "ip_address": "219.84.169.100"
    }, {
        "id": 20,
        "first_name": "Vern",
        "last_name": "See",
        "email": "vseej@hexun.com",
        "gender": "Male",
        "ip_address": "32.80.133.199"
    }, {
        "id": 21,
        "first_name": "Marylin",
        "last_name": "Eve",
        "email": "mevek@opensource.org",
        "gender": "Female",
        "ip_address": "229.181.86.88"
    }, {
        "id": 22,
        "first_name": "Tobe",
        "last_name": "Robbie",
        "email": "trobbiel@hexun.com",
        "gender": "Polygender",
        "ip_address": "0.137.218.202"
    }, {
        "id": 23,
        "first_name": "Waylan",
        "last_name": "Jewar",
        "email": "wjewarm@home.pl",
        "gender": "Male",
        "ip_address": "94.250.196.64"
    }, {
        "id": 24,
        "first_name": "Emanuele",
        "last_name": "Tarbet",
        "email": "etarbetn@fc2.com",
        "gender": "Male",
        "ip_address": "91.145.12.74"
    }, {
        "id": 25,
        "first_name": "Marius",
        "last_name": "Wakefield",
        "email": "mwakefieldo@indiatimes.com",
        "gender": "Male",
        "ip_address": "243.84.204.143"
    }, {
        "id": 26,
        "first_name": "Isidro",
        "last_name": "Temprell",
        "email": "itemprellp@nbcnews.com",
        "gender": "Genderqueer",
        "ip_address": "224.57.73.80"
    }, {
        "id": 27,
        "first_name": "Kizzie",
        "last_name": "Hunnisett",
        "email": "khunnisettq@printfriendly.com",
        "gender": "Female",
        "ip_address": "235.69.189.152"
    }, {
        "id": 28,
        "first_name": "Reba",
        "last_name": "McKenzie",
        "email": "rmckenzier@ning.com",
        "gender": "Female",
        "ip_address": "129.134.100.126"
    }, {
        "id": 29,
        "first_name": "Kellina",
        "last_name": "Grady",
        "email": "kgradys@newsvine.com",
        "gender": "Female",
        "ip_address": "223.155.57.189"
    }, {
        "id": 30,
        "first_name": "Kizzee",
        "last_name": "Emerson",
        "email": "kemersont@xrea.com",
        "gender": "Female",
        "ip_address": "224.227.134.9"
    }
];

// ctrl + ~ => terminal
// cmd + ~ => terminal

// git config: chạy 1 lần thôi

// khởi tạo git trong project: git init
// tạo remote: git remote add <tên remote> <url>
// tạo branch chính: git branch -M <tên branch> 

// thêm file vào staging area: git add .


